"""Generate results/DOCUMENTATION_INDEX.md — a map of every artifact on disk.

The project produces a lot of small files: per-run configs, logs, metrics,
prediction tables, nine derived tables, two figure manifests. Six months from
now, or to an examiner opening the repository for the first time, that is a pile
rather than a record. This walks what actually exists and writes an index saying
what each artifact is, what produced it, and what it is for.

It is generated, never hand-maintained, so it cannot drift out of date the way a
hand-written inventory always does. Run it last in the pipeline.
"""
import json
from datetime import datetime
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
RESULTS = REPO_ROOT / "results"

TABLE_DESC = {
    "master.csv": ("One row per run: config, clean metrics, every corruption cell and "
                   "frequency point. THE source of truth — every reported number "
                   "traces here.", "src/analysis/aggregate.py"),
    "curves_long.csv": ("Long format (run, curve, x, accuracy) for plotting and "
                        "grouping over seeds.", "src/analysis/aggregate.py"),
    "per_class.csv": ("Per-class accuracy for every run — the rare-class axis.",
                      "src/analysis/aggregate.py"),
    "lr_sweep.csv": ("The declared per-model LR sweeps and which point was selected. "
                     "Evidence for the 'declared per-model tuning' claim.",
                     "src/analysis/aggregate.py"),
    "deployment.csv": ("Static cost (params, FLOPs) joined to measured cost (peak "
                       "VRAM, throughput).", "src/analysis/aggregate.py"),
    "compute_ledger.csv": ("Where the GPU-hours went, per block.",
                           "src/analysis/aggregate.py"),
    "calibration.csv": ("ECE, MCE, mean confidence and over-confidence gap per run.",
                        "src/analysis/calibration.py"),
    "reliability.csv": ("Per-bin reliability data behind the diagrams.",
                        "src/analysis/calibration.py"),
    "error_overlap.csv": ("Matched-pair agreement: kappa, shared wrong labels, oracle "
                          "headroom.", "src/analysis/error_overlap.py"),
    "model_cost.csv": ("Params / GMACs / feature dim, measured with torch's FLOP "
                       "counter.", "src/utils/provenance.py"),
    "environment.json": ("Machine, driver, kernel, library versions and git commit at "
                         "capture time.", "src/utils/provenance.py"),
}

RUN_FILES = [
    ("config.yaml", "The exact merged config the run used — base <- model <- data <- CLI."),
    ("train_log.csv", "Per epoch: losses, top-1/top-5, LR, epoch time, imgs/sec, peak VRAM."),
    ("metrics.json", "Run summary: best val top-1, best epoch, params, VRAM, wall time, "
                     "library versions. Its existence marks the run complete."),
    ("clean_eval.json", "Frozen-test top-1/top-5/macro-F1 plus per-class accuracy."),
    ("predictions.parquet", "Per-image: filepath, true label, prediction, confidence. "
                            "Raw material for calibration and error overlap."),
    ("eval_results.json", "The 42-pass battery: corruptions x severities, frequency "
                          "sweeps, band-limited noise."),
]


def main():
    lines = [f"# Documentation index",
             "",
             f"*Generated by `src/analysis/docs_index.py` on "
             f"{datetime.now():%Y-%m-%d %H:%M}. Do not edit by hand — re-run it.*",
             "",
             "Every figure and table in the report and the decks is produced by script "
             "from the files below. No number in any deliverable is entered by hand.",
             ""]

    # --- runs -------------------------------------------------------------
    runs = sorted(p for p in (RESULTS / "runs").iterdir() if p.is_dir()) \
        if (RESULTS / "runs").is_dir() else []
    complete = [r for r in runs if (r / "metrics.json").exists()]
    sweeps = [r for r in complete if "sweep" in r.name]
    matrix = [r for r in complete if "sweep" not in r.name]
    lines += ["## Runs", "",
              f"- **{len(matrix)}** matrix runs complete, **{len(sweeps)}** LR-sweep runs.",
              f"- Run ID format: `{{model}}_{{dataset}}_f{{fraction}}_s{{seed}}_{{regime}}`.",
              "- Each `results/runs/<run_id>/` contains:", ""]
    lines += [f"  | File | What it is |", "  |---|---|"]
    for name, desc in RUN_FILES:
        n = sum(1 for r in runs if (r / name).exists())
        lines.append(f"  | `{name}` | {desc} *(present in {n} runs)* |")
    lines.append("")
    if matrix:
        by = {}
        for r in matrix:
            m = json.loads((r / "metrics.json").read_text())
            by.setdefault((m["dataset"], m["regime"], m["model_name"]), []).append(m)
        lines += ["| Dataset | Regime | Model | Runs | Fractions | Seeds |", "|---|---|---|---|---|---|"]
        for (ds, rg, mdl), ms in sorted(by.items()):
            fr = sorted({m["fraction"] for m in ms})
            sd = sorted({m["seed"] for m in ms})
            lines.append(f"| {ds} | {rg} | {mdl} | {len(ms)} | {fr} | {sd} |")
        lines.append("")

    # --- tables -----------------------------------------------------------
    lines += ["## Derived tables (`results/tables/`)", "",
              "| File | Rows | What it is | Produced by |", "|---|---|---|---|"]
    for name, (desc, src) in TABLE_DESC.items():
        p = RESULTS / "tables" / name
        if not p.exists():
            continue
        rows = "—"
        if name.endswith(".csv"):
            try:
                rows = f"{len(pd.read_csv(p)):,}"
            except Exception:
                pass
        lines.append(f"| `{name}` | {rows} | {desc} | `{src}` |")
    lines.append("")

    # --- figures ----------------------------------------------------------
    for label, man in (("Quantitative figures (`results/figures/`)",
                        RESULTS / "figures" / "MANIFEST.csv"),
                       ("Qualitative assets (`results/figures/assets/`)",
                        RESULTS / "figures" / "assets" / "MANIFEST.csv")):
        if not man.exists():
            continue
        df = pd.read_csv(man)
        lines += [f"## {label}", "",
                  "| File | Title | Caption | Defined by |", "|---|---|---|---|"]
        srccol = "generated_from" if "generated_from" in df.columns else "defined_by"
        for _, r in df.iterrows():
            lines.append(f"| `{r['file']}` | {r['title']} | {r['caption']} | "
                         f"`{r[srccol]}` |")
        lines += ["", "*Each figure is written as both `.png` (slides) and `.pdf` "
                      "(report, vector).*", ""]

    # --- deliverables -----------------------------------------------------
    deck_dir = REPO_ROOT / "report" / "phase1" / "decks"
    docs = sorted(deck_dir.glob("*.pptx")) if deck_dir.is_dir() else []
    reports = sorted((REPO_ROOT / "report" / "phase1").glob("*.docx"))
    if docs or reports:
        lines += ["## Deliverables (local, not in git)", "",
                  "| File | What it is |", "|---|---|"]
        for p in docs + reports:
            lines.append(f"| `{p.relative_to(REPO_ROOT)}` | "
                         f"generated by `report/build/` from `results/tables/` |")
        lines.append("")

    lines += ["## Reproducing everything", "",
              "```bash",
              "bash scripts/run_lr_sweep_resnet50.sh   # declared LR sweep, CNN",
              "bash scripts/run_lr_sweep_vit_b16.sh    # declared LR sweep, ViT",
              "bash scripts/run_pipeline.sh            # matrix -> probes -> battery -> analysis",
              "FOOD101=1 bash scripts/run_pipeline.sh  # ... and the Food-101 block",
              "python report/build/build_decks.py      # six decks",
              "python report/build/build_reports.py    # two reports",
              "```", ""]

    out = RESULTS / "DOCUMENTATION_INDEX.md"
    out.write_text("\n".join(lines))
    print(f"[docs] {out.relative_to(REPO_ROOT)}  ({len(lines)} lines)")
    _update_readme_status()


def _update_readme_status():
    """Refresh the generated status block in README.md.

    The README is the repository's public face, so a stale hand-written status
    line there is worse than none. The block between the two markers is owned by
    this function; everything outside it is hand-written prose.
    """
    import sys
    sys.path.insert(0, str(REPO_ROOT / "report" / "build"))
    from facts import Facts

    f = Facts()
    readme = REPO_ROOT / "README.md"
    if not readme.exists():
        return
    START, END = "<!-- STATUS:BEGIN -->", "<!-- STATUS:END -->"
    text = readme.read_text()
    if START not in text or END not in text:
        return

    av = f.available()
    d = f.dataset_facts()
    # Completeness is a COUNT, never "does at least one exist" — a block that is
    # 14/24 done must not report itself complete on the repository's front page.
    N_FULLFT, N_PROBE, N_FOOD = 24, 24, 4
    n_food = 0 if f.master.empty else int((f.master["dataset"] == "food101").sum())
    rows = ["| Block | Status |", "|---|---|"]
    for label, done, total, detail in [
        ("Frozen splits", 1, 1,
         f"{d['total']:,} images / {d['classes']} classes, {d['train_f100']:,} train · "
         f"{d['val']:,} val · {d['test']:,} frozen test"),
        ("Declared LR sweeps", int(f.lr_selected("resnet50") != "(pending)")
         + int(f.lr_selected("vit_b16") != "(pending)"), 2,
         f"ResNet-50 {f.lr_selected('resnet50')} · ViT-B/16 {f.lr_selected('vit_b16')}"),
        ("Caltech-256 full fine-tune", f.n_runs("fullft"), N_FULLFT,
         f"{f.n_runs('fullft')} of {N_FULLFT} runs"),
        ("Linear probes", f.n_runs("linprobe"), N_PROBE,
         f"{f.n_runs('linprobe')} of {N_PROBE} runs"),
        ("Evaluation battery", f.battery_done(), N_FULLFT,
         f"{f.battery_done()} of {N_FULLFT} checkpoints × 42 inference passes"),
        ("Food-101 confirmation", n_food, N_FOOD, f"{n_food} of {N_FOOD} runs"),
    ]:
        state = "complete" if done >= total else ("in progress" if done else "not started")
        rows.append(f"| {label} | {state} — {detail} |")

    eff = ["", "Frozen-test top-1, mean ± SD over 3 seeds:", "",
           "| Model | 10% | 25% | 50% | 100% |", "|---|---|---|---|---|"]
    any_row = False
    for m, name in (("resnet50", "ResNet-50"), ("vit_b16", "ViT-B/16")):
        if f.top1(m, 100) is None and f.top1(m, 10) is None:
            continue
        e = f.efficiency_row(m)
        eff.append(f"| {name} | {e[10]} | {e[25]} | {e[50]} | {e[100]} |")
        any_row = True
    block = [START, "", *rows, *(eff if any_row else []), "",
             f"*Generated by `src/analysis/docs_index.py` — "
             f"{f.gpu_hours()} GPU-hours on one RTX 4060 8 GB.*", "", END]
    new_text = text[:text.index(START)] + "\n".join(block) + text[text.index(END) + len(END):]
    readme.write_text(new_text)
    print(f"[docs] README.md status block refreshed")


if __name__ == "__main__":
    main()
